[package]
name = "nice-number"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nn"
path = "src/main.rs"

[dependencies]
num-format = "0.4"
colored = "2.1"
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
